/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controle.CadastroMedico;
import Controle.CadastroPaciente;
import Controle.ConsultaCount;
import Controle.Consulta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class TelaPrincipal extends javax.swing.JFrame 
{   
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal()
    {
        initComponents();
        ListarPacientes();
        ListarMedico();
        ListarEspecialidadMedico();
        System.out.println("oi");
    }
    
    public void exibirDadosPaciente(javax.swing.JTable table)
    {
        CadastroPaciente paciente = new CadastroPaciente();
        ArrayList<CadastroPaciente> exibirInfo =  paciente.ExibirPaciente();
        DefaultTableModel md = (DefaultTableModel) this.tbDadosPaciente.getModel();
        md.setNumRows(0);
        for (int i=0; i < exibirInfo.size(); i++)
        {
             md.addRow(new Object[]{exibirInfo.get(i).getCpf(),exibirInfo.get(i).getNome(),exibirInfo.get(i).getTel(),exibirInfo.get(i).getEndereco()});
        }
    }

    public void exibirDadosMedicos(javax.swing.JTable table)
{
    CadastroMedico medico = new CadastroMedico();
    //ArrayList<CadastroMedico> exibirInfo = new ArrayList<CadastroMedico>();
    ArrayList<CadastroMedico> exibirInfo = medico.ExibirMedico();  
       DefaultTableModel md = (DefaultTableModel) this.tbDadosMedico.getModel();
       md.setRowCount(0);
       for (int i=0; i < exibirInfo.size(); i++)
       {
            md.addRow(new Object[]{exibirInfo.get(i).getCrm(),exibirInfo.get(i).getNome(),exibirInfo.get(i).getTel(),exibirInfo.get(i).getEspecialidade()});
       }
} 

    
    public void exibirConsulta(javax.swing.JTable table)
    {
        Consulta consulta = new Consulta();
        //ArrayList<CadastroMedico> exibirInfo = new ArrayList<CadastroMedico>();
        ArrayList<Consulta> exibirInfo = consulta.ExibirConsultas();
        DefaultTableModel md = (DefaultTableModel) this.tbDadosConsulta.getModel();
        md.setRowCount(0);
        for (int i=0; i < exibirInfo.size(); i++)
        {
             md.addRow(new Object[]{exibirInfo.get(i).getId(),exibirInfo.get(i).getCrm(),exibirInfo.get(i).getCpf(),exibirInfo.get(i).getData()});
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPaneAgConsulta = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTcodconsulta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDadosConsulta = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jBpesquisar = new javax.swing.JButton();
        cbMedico = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbPaciente = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jBadicionar = new javax.swing.JButton();
        jBinserirConsulta = new javax.swing.JButton();
        jBcancelarConsulta = new javax.swing.JButton();
        jBexcluirconsulta = new javax.swing.JButton();
        jBsalvararconsulta = new javax.swing.JButton();
        jFdatadaconsulta = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        cbEspecialidade = new javax.swing.JComboBox<>();
        jTEspecialidade2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jBsalvarM = new javax.swing.JButton();
        jBinserirM = new javax.swing.JButton();
        jTNome1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTcrm = new javax.swing.JTextField();
        jFtelefone1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTespecialidade = new javax.swing.JTextField();
        jBagConsultaCadMedico = new javax.swing.JButton();
        jBcancelar1 = new javax.swing.JButton();
        jBexcluirMd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDadosMedico = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        JTcpf = new javax.swing.JFormattedTextField();
        jBnovoP = new javax.swing.JButton();
        jBsalvarP = new javax.swing.JButton();
        jBinserirP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDadosPaciente = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jFTelefone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTendereco = new javax.swing.JTextField();
        jBexcluir = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBagConsultaCadPaciente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbQuantConsultas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTtotalconsultas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBAtualizarQTN = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jLabel5.setText("Deseja realmente cadastrar este paciente?");

        jButton2.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jButton2.setText("SIM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jButton3.setText("NÃO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel5)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema - Tela Principal");

        jTabbedPaneAgConsulta.setFont(new java.awt.Font("Comfortaa", 0, 11)); // NOI18N
        jTabbedPaneAgConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneAgConsultaMouseClicked(evt);
            }
        });
        jTabbedPaneAgConsulta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPaneAgConsultaComponentShown(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel18.setText("Consultas agendadas");

        jTcodconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodconsultaActionPerformed(evt);
            }
        });

        tbDadosConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "MEDICO", "ESPECIALIDADE", "CPF", "DATA/HORA"
            }
        ));
        tbDadosConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosConsultaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDadosConsulta);

        jLabel19.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel19.setText("Codigo Consulta");

        jBpesquisar.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jBpesquisar.setText("Pesquisar");
        jBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarActionPerformed(evt);
            }
        });

        cbMedico.setEnabled(false);
        cbMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMedicoMouseClicked(evt);
            }
        });
        cbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel20.setText("Medico");

        jLabel21.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel21.setText("Paciente");

        cbPaciente.setEnabled(false);
        cbPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbPacienteMouseClicked(evt);
            }
        });
        cbPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPacienteActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel22.setText("Data da consulta");

        jBadicionar.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jBadicionar.setText("Adicionar");
        jBadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadicionarActionPerformed(evt);
            }
        });

        jBinserirConsulta.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jBinserirConsulta.setText("Inserir");
        jBinserirConsulta.setEnabled(false);
        jBinserirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirConsultaActionPerformed(evt);
            }
        });

        jBcancelarConsulta.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jBcancelarConsulta.setText("Cancelar");
        jBcancelarConsulta.setEnabled(false);
        jBcancelarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarConsultaActionPerformed(evt);
            }
        });

        jBexcluirconsulta.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jBexcluirconsulta.setText("Excluir");
        jBexcluirconsulta.setEnabled(false);
        jBexcluirconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirconsultaActionPerformed(evt);
            }
        });

        jBsalvararconsulta.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jBsalvararconsulta.setText("Salvar");
        jBsalvararconsulta.setEnabled(false);
        jBsalvararconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvararconsultaActionPerformed(evt);
            }
        });

        try {
            jFdatadaconsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFdatadaconsulta.setPreferredSize(new java.awt.Dimension(180, 40));

        jLabel23.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel23.setText("Especialidade");

        cbEspecialidade.setEnabled(false);
        cbEspecialidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbEspecialidadeMouseClicked(evt);
            }
        });
        cbEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(139, 139, 139)
                                        .addComponent(jTEspecialidade2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTcodconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBcancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBinserirConsulta)
                                .addGap(12, 12, 12)
                                .addComponent(jBsalvararconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(jBexcluirconsulta)))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(cbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFdatadaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(65, 65, 65))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcodconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBinserirConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexcluirconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalvararconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFdatadaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTEspecialidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(148, 148, 148)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPaneAgConsulta.addTab("Consultas", jPanel1);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jButton4.setText("Novo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jBsalvarM.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBsalvarM.setText("Salvar");
        jBsalvarM.setFocusCycleRoot(true);
        jBsalvarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarMActionPerformed(evt);
            }
        });

        jBinserirM.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBinserirM.setText("Inserir");
        jBinserirM.setFocusCycleRoot(true);
        jBinserirM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirMActionPerformed(evt);
            }
        });

        jTNome1.setFocusCycleRoot(true);
        jTNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNome1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel10.setText("Nome:");

        jLabel11.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel11.setText("CRM");

        jTcrm.setFocusCycleRoot(true);

        try {
            jFtelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel14.setText("Telefone");

        jLabel16.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel16.setText("Especialidade");

        jTespecialidade.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jTespecialidade.setMinimumSize(new java.awt.Dimension(10, 35));
        jTespecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTespecialidadeActionPerformed(evt);
            }
        });

        jBagConsultaCadMedico.setFont(new java.awt.Font("Comfortaa", 0, 13)); // NOI18N
        jBagConsultaCadMedico.setText("Agendar Consultas");
        jBagConsultaCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagConsultaCadMedicoActionPerformed(evt);
            }
        });

        jBcancelar1.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBcancelar1.setText("Cancelar");
        jBcancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelar1ActionPerformed(evt);
            }
        });

        jBexcluirMd.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBexcluirMd.setText("Excluir");
        jBexcluirMd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirMdActionPerformed(evt);
            }
        });

        tbDadosMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CRM", "NOME", "TELEFONE", "ESPECIALIDDE"
            }
        ));
        tbDadosMedico.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbDadosMedicoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbDadosMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosMedicoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDadosMedico);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBsalvarM)
                                .addGap(18, 18, 18)
                                .addComponent(jBinserirM)
                                .addGap(18, 18, 18)
                                .addComponent(jBcancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBexcluirMd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jBagConsultaCadMedico)))
                        .addContainerGap(259, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTNome1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jTcrm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jFtelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(146, 146, 146)
                                                .addComponent(jLabel14)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jTespecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))
                        .addGap(157, 157, 157))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalvarM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBinserirM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBagConsultaCadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexcluirMd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTespecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTcrm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFtelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPaneAgConsulta.addTab("Cadastro Medico", jPanel3);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel2.setText("CPF:");

        jTNome.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jTNome.setFocusCycleRoot(true);
        jTNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeActionPerformed(evt);
            }
        });

        try {
            JTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JTcpf.setFocusCycleRoot(true);
        JTcpf.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        JTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcpfActionPerformed(evt);
            }
        });

        jBnovoP.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBnovoP.setText("Novo");
        jBnovoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoPActionPerformed(evt);
            }
        });

        jBsalvarP.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBsalvarP.setText("Salvar");
        jBsalvarP.setEnabled(false);
        jBsalvarP.setFocusCycleRoot(true);
        jBsalvarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarPActionPerformed(evt);
            }
        });

        jBinserirP.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBinserirP.setText("Inserir");
        jBinserirP.setFocusCycleRoot(true);
        jBinserirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirPActionPerformed(evt);
            }
        });

        tbDadosPaciente.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        tbDadosPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "NOME", "TELEFONE", "ENDEREÇO"
            }
        ));
        tbDadosPaciente.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbDadosPacienteAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbDadosPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDadosPaciente);

        jLabel7.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel7.setText("Telefone");

        try {
            jFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTelefone.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel8.setText("Endereço");

        jTendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTenderecoActionPerformed(evt);
            }
        });

        jBexcluir.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBcancelar.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBagConsultaCadPaciente.setFont(new java.awt.Font("Comfortaa", 0, 13)); // NOI18N
        jBagConsultaCadPaciente.setText("Agendar Consultas");
        jBagConsultaCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagConsultaCadPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTendereco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(464, 464, 464))
                                            .addComponent(jTNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(252, 252, 252))))
                        .addContainerGap(220, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBnovoP)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalvarP)
                        .addGap(18, 18, 18)
                        .addComponent(jBinserirP)
                        .addGap(18, 18, 18)
                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBagConsultaCadPaciente)
                        .addGap(210, 210, 210))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBagConsultaCadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBnovoP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBsalvarP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBinserirP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jTabbedPaneAgConsulta.addTab("Cadastro Paciente", jPanel2);

        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentShown(evt);
            }
        });

        tbQuantConsultas.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        tbQuantConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CRM", "NOME", "QNT"
            }
        ));
        tbQuantConsultas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbQuantConsultasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbQuantConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuantConsultasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbQuantConsultas);

        jLabel3.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel3.setText("Total de consultas");

        jLabel4.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        jLabel4.setText("Quantitativo de consultas medicas");

        jBAtualizarQTN.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N
        jBAtualizarQTN.setText("Atualizar");
        jBAtualizarQTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarQTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTtotalconsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAtualizarQTN)))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAtualizarQTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTtotalconsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTabbedPaneAgConsulta.addTab("Relatorio", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAgConsulta)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAgConsulta)
        );

        setSize(new java.awt.Dimension(1040, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeActionPerformed

    private void jBnovoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoPActionPerformed
        // Botão novo cadastro paciente, habilita campos para preenchimento.
        jBsalvarP.setEnabled(false);       
        jTNome.setEnabled(true);
        JTcpf.setEnabled(true);
        jFTelefone.setEnabled(true);
        jTendereco.setEnabled(true);
        jBinserirP.setEnabled(true);
        jBnovoP.setEnabled(false);
        exibirDadosPaciente(tbDadosPaciente);
    }//GEN-LAST:event_jBnovoPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBinserirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirPActionPerformed
        // Botao salvar cadastro paciente
        Controle.CadastroPaciente cl=new Controle.CadastroPaciente();
        cl.setNome(this.jTNome.getText());
        cl.setCpf(this.JTcpf.getText());
        cl.setTel(this.jFTelefone.getText());
        cl.setEndereco(this.jTendereco.getText());
        cl.Inserir();
        jTNome.setEnabled(false);
        JTcpf.setEnabled(false);
        jFTelefone.setEnabled(false);
        jTendereco.setEnabled(false);
        jTNome.setText("");
        JTcpf.setText("");
        jFTelefone.setText("");
        jTendereco.setText("");
        exibirDadosPaciente(tbDadosPaciente);
    }//GEN-LAST:event_jBinserirPActionPerformed

    private void jTenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTenderecoActionPerformed

    private void jTespecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTespecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTespecialidadeActionPerformed

    private void jTNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNome1ActionPerformed

    private void jBinserirMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirMActionPerformed
        // botao salvar cadastro medico
        CadastroMedico cl=new CadastroMedico();
        cl.setNome(this.jTNome1.getText());
        cl.setEspecialidade(this.jTespecialidade.getText());
        cl.setCrm(this.jTcrm.getText());
        cl.setTel(this.jFtelefone1.getText());
        cl.Inserir();
        this.exibirDadosMedicos(tbDadosMedico);
    }//GEN-LAST:event_jBinserirMActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Botão novo cadastro paciente, habilita campos para preenchimento.
        jBsalvarM.setEnabled(false);
        jBinserirM.setEnabled(true);
        jTNome1.setEnabled(true);
        jTcrm.setEnabled(true);
        jTespecialidade.setEnabled(true);
        jFtelefone1.setEnabled(true);
        this.exibirDadosMedicos(tbDadosMedico);
        //AtualizarMedico();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTcodconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodconsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodconsultaActionPerformed

    private void jBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarActionPerformed
        //botao de pesquisa da tela de consulta
        jBexcluirconsulta.setEnabled(true);
        jBsalvararconsulta.setEnabled(true);
        jBinserirConsulta.setEnabled(true);
        jBcancelarConsulta.setEnabled(true);
        cbMedico.setEnabled(true);
        cbPaciente.setEnabled(true);
        jFdatadaconsulta.setEnabled(true);
        
        Consulta ag = new Consulta();
        ag.getConsulta(jTcodconsulta.getText());
        
        jFdatadaconsulta.setText(ag.getData());
        Object obj = cbMedico.getSelectedItem();
        cbMedico.setSelectedItem(ag.getCrm());
        obj = cbMedico.getSelectedItem();
        cbMedico.setSelectedItem(obj);
        
        obj = cbPaciente.getSelectedItem();
        cbPaciente.setSelectedItem(ag.getCpf());
        obj = cbPaciente.getSelectedItem();
        cbPaciente.setSelectedItem(obj);
    }//GEN-LAST:event_jBpesquisarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // Botão cancelar cadastro paciente
        jTNome.setEnabled(false);
        JTcpf.setEnabled(false);
        jFTelefone.setEnabled(false);
        jTendereco.setEnabled(false);
        jBsalvarP.setEnabled(false);
        jBinserirP.setEnabled(false);  
        tbDadosPaciente.setEnabled(false);        
        jTNome.setText("");
        JTcpf.setText("");
        jFTelefone.setText("");
        jTendereco.setText("");

    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBagConsultaCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagConsultaCadPacienteActionPerformed
        // Botao de agendar consulta da tela cadastro paciente
        this.jTabbedPaneAgConsulta.setSelectedIndex(0);
    }//GEN-LAST:event_jBagConsultaCadPacienteActionPerformed

    private void jBagConsultaCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagConsultaCadMedicoActionPerformed
        // Botao de agendar consulta da tela cadastro medico
        this.jTabbedPaneAgConsulta.setSelectedIndex(0);
    }//GEN-LAST:event_jBagConsultaCadMedicoActionPerformed

    private void jBcancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelar1ActionPerformed
        // botao cancelar da tela de cadastro medico
        jBsalvarM.setEnabled(false);
        jBinserirM.setEnabled(false);
        jTNome1.setEnabled(false);
        jTcrm.setEnabled(false);
        jTespecialidade.setEnabled(false);
        jFtelefone1.setEnabled(false);
        jBadicionar.setEnabled(true);
    }//GEN-LAST:event_jBcancelar1ActionPerformed

    private void cbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedicoActionPerformed

    private void cbPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPacienteActionPerformed

    private void jBadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadicionarActionPerformed
        // botao adicionar da tela de consulta

        jBinserirConsulta.setEnabled(true);
        jBagConsultaCadMedico.setEnabled(true);
        jBcancelarConsulta.setEnabled(true);
        cbMedico.setEnabled(true);
        cbPaciente.setEnabled(true);
        cbEspecialidade.setEnabled(true);
        jFdatadaconsulta.setEnabled(true);
        tbDadosConsulta.setEnabled(true);
        jBexcluirconsulta.setEnabled(true);
        //jBsalvararconsulta.setEnabled(true);
        jTcodconsulta.setEnabled(false);
        jBpesquisar.setEnabled(false);
        jBadicionar.setEnabled(false);
    }//GEN-LAST:event_jBadicionarActionPerformed

    private void jBinserirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirConsultaActionPerformed
        //botao salvar da tela de consulta
        Consulta cl= new Consulta();
        cl.setCrm(this.cbMedico.getSelectedItem().toString());
        cl.setCpf(this.cbPaciente.getSelectedItem().toString());
        cl.setData(this.jFdatadaconsulta.getText());
        cl.setEspecialidade(this.cbEspecialidade.toString());
        cl.Inserir(this.jFdatadaconsulta.getText());
        this.exibirConsulta(tbDadosConsulta);  
        jBadicionar.setEnabled(true);
        jBinserirConsulta.setEnabled(false);
        jTcodconsulta.setText("");
        
    }//GEN-LAST:event_jBinserirConsultaActionPerformed

    private void jBcancelarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarConsultaActionPerformed
        // botao cancelar da tela de consulta

        jBinserirConsulta.setEnabled(false);
        jBagConsultaCadMedico.setEnabled(false);
        jBcancelarConsulta.setEnabled(false);
        cbMedico.setEnabled(false);
        cbPaciente.setEnabled(false);
        cbEspecialidade.setEnabled(false);
        jFdatadaconsulta.setEnabled(false);
        tbDadosConsulta.setEnabled(false);
        jBexcluirconsulta.setEnabled(false);
        jTcodconsulta.setEnabled(true);
        jBpesquisar.setEnabled(true);
        jBadicionar.setEnabled(true);
        jBagConsultaCadMedico.setText("");
        jFdatadaconsulta.setText("");

    }//GEN-LAST:event_jBcancelarConsultaActionPerformed

    private void jBexcluirMdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirMdActionPerformed
        // botao excluir da tela cadastro medico
        
        CadastroMedico cl=new CadastroMedico();
        cl.setNome(this.jTNome1.getText());
        cl.setEspecialidade(this.jTespecialidade.getText());
        cl.setCrm(this.jTcrm.getText());
        cl.setTel(this.jFtelefone1.getText());
        cl.ExcluirMedico();
        this.exibirDadosMedicos(tbDadosMedico);
        
    }//GEN-LAST:event_jBexcluirMdActionPerformed

    private void tbDadosMedicoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbDadosMedicoAncestorAdded
        // tabela de informacoes cadastro medico
    }//GEN-LAST:event_tbDadosMedicoAncestorAdded

    private void tbDadosPacienteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbDadosPacienteAncestorAdded
        // tabela de informacoes cadastro paciente
    }//GEN-LAST:event_tbDadosPacienteAncestorAdded

    private void jBexcluirconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirconsultaActionPerformed
        // botao para excluir consulta
        Consulta cl = new Consulta();
        cl.ExcluirAg(this.jTcodconsulta.getText());
        
        this.exibirConsulta(tbDadosConsulta);    
    }//GEN-LAST:event_jBexcluirconsultaActionPerformed

    private void jBsalvararconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvararconsultaActionPerformed
        // botao editar consulta
        System.out.println("arg: "+ this.jTcodconsulta.getText() + "-" + this.cbPaciente.getSelectedItem().toString() + "-" +  this.cbMedico.getSelectedItem().toString()+ "-" +  this.cbEspecialidade.getSelectedItem().toString() + "-" +  this.jFdatadaconsulta.getText());
        Consulta cl = new Consulta();
        cl.EditarAg(this.jTcodconsulta.getText(), this.cbPaciente.getSelectedItem().toString(), this.cbMedico.getSelectedItem().toString(), this.cbEspecialidade.getSelectedItem().toString(),this.jFdatadaconsulta.getText());
        jBexcluirconsulta.setEnabled(true);
        jBcancelarConsulta.setEnabled(true);
        jBinserirConsulta.setEnabled(true);
 
        this.exibirConsulta(tbDadosConsulta);
    }//GEN-LAST:event_jBsalvararconsultaActionPerformed

    private void JTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcpfActionPerformed

    private void jBsalvarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarPActionPerformed
        
        CadastroPaciente pc = new CadastroPaciente();
        pc.EditarPc(this.JTcpf.getText(), this.jTNome.getText(), this.jFTelefone.getText(), this.jTendereco.getText());
        
        jBsalvarP.setEnabled(false);
        this.exibirDadosPaciente(tbDadosPaciente);
    }//GEN-LAST:event_jBsalvarPActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:
        CadastroPaciente cl=new CadastroPaciente();
        cl.setCpf(this.JTcpf.getText());
        cl.setNome(this.jTNome.getText());
        cl.setTel(this.jFTelefone.getText());
        cl.setEndereco(this.jTendereco.getText());
        cl.ExcluirPaciente();
        jTNome.setText("");
        JTcpf.setText("");
        jFTelefone.setText("");
        jTendereco.setText("");

        this.exibirDadosPaciente(tbDadosPaciente);
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jTabbedPaneAgConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneAgConsultaMouseClicked
        // TODO add your handling code here:
        System.out.println("aba cadastro consulta");

    }//GEN-LAST:event_jTabbedPaneAgConsultaMouseClicked

    private void jTabbedPaneAgConsultaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPaneAgConsultaComponentShown

    }//GEN-LAST:event_jTabbedPaneAgConsultaComponentShown

    private void jBsalvarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarMActionPerformed

        CadastroMedico md = new CadastroMedico();
        md.EditarMd(this.jTcrm.getText(), this.jTNome1.getText(), this.jFtelefone1.getText(), this.jTespecialidade.getText());
 
        exibirDadosMedicos(tbDadosMedico);
    }//GEN-LAST:event_jBsalvarMActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        System.out.println("Iniciando funcão de exibir paciente");
        this.exibirDadosPaciente(tbDadosPaciente);
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
        System.out.println("Iniciando funcão de exibir medico");
        exibirDadosMedicos(tbDadosMedico);
    }//GEN-LAST:event_jPanel3ComponentShown

    private void cbMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMedicoMouseClicked
        // TODO add your handling code here:
        ListarMedico();
        ListarEspecialidadMedico();
    }//GEN-LAST:event_cbMedicoMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void cbPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPacienteMouseClicked
        // TODO add your handling code here:
        ListarPacientes();
    }//GEN-LAST:event_cbPacienteMouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        exibirConsulta(tbDadosConsulta);
    }//GEN-LAST:event_jPanel1ComponentShown

    private void tbDadosConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosConsultaMouseClicked
        // TODO add your handling code here:
        jBsalvararconsulta.setEnabled(true);
        jBexcluirconsulta.setEnabled(true);
        jBcancelarConsulta.setEnabled(true);

        this.setEnebleAll();
        int linha = this.tbDadosConsulta.getSelectedRow();
        String cod = String.valueOf(tbDadosConsulta.getModel().getValueAt(linha, 0));
        String med = String.valueOf(tbDadosConsulta.getModel().getValueAt(linha, 1));
        String pac = String.valueOf(tbDadosConsulta.getModel().getValueAt(linha, 2));
        String date = String.valueOf(tbDadosConsulta.getModel().getValueAt(linha, 3));
        
        Object obj = cbMedico.getSelectedItem();
        cbMedico.setSelectedItem(med);
        obj = cbMedico.getSelectedItem();
        cbMedico.setSelectedItem(obj);
        
        obj = cbPaciente.getSelectedItem();
        cbPaciente.setSelectedItem(pac);
        obj = cbPaciente.getSelectedItem();
        cbPaciente.setSelectedItem(obj);
        
        jTcodconsulta.setText(cod);

        this.jFdatadaconsulta.setText(date);
        System.out.println("eu sou :" + cod + "-" + med + "-" + pac + "-" + date);
        
        

    }//GEN-LAST:event_tbDadosConsultaMouseClicked

    private void tbDadosPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosPacienteMouseClicked
        
        this.setEnebleAll();
        int linha = this.tbDadosPaciente.getSelectedRow();
        String cpf = String.valueOf(tbDadosPaciente.getModel().getValueAt(linha, 0));
        String nome = String.valueOf(tbDadosPaciente.getModel().getValueAt(linha, 1));
        String tel = String.valueOf(tbDadosPaciente.getModel().getValueAt(linha, 2));
        String end = String.valueOf(tbDadosPaciente.getModel().getValueAt(linha, 3));
        
        JTcpf.setText(cpf);
        jTNome.setText(nome);
        jFTelefone.setText(tel);
        jTendereco.setText(end);
        
        jBsalvarP.setEnabled(true);
        
    }//GEN-LAST:event_tbDadosPacienteMouseClicked

    private void tbQuantConsultasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbQuantConsultasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbQuantConsultasAncestorAdded

    private void tbQuantConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuantConsultasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbQuantConsultasMouseClicked

    private void jBAtualizarQTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarQTNActionPerformed
        Consulta c = new Consulta();
        ArrayList<ConsultaCount> cCount = c.consultaCount();
        DefaultTableModel md = (DefaultTableModel) this.tbQuantConsultas.getModel();
        md.setNumRows(0);
        int totalConsultas = 0;
        for (int i=0; i < cCount.size(); i++)
        {
             md.addRow(new Object[]{cCount.get(i).crm, cCount.get(i).nome, cCount.get(i).qnt});
             totalConsultas += Integer.parseInt(cCount.get(i).qnt);
        }
        jTtotalconsultas.setText(Integer.toString(totalConsultas));
    }//GEN-LAST:event_jBAtualizarQTNActionPerformed

    private void tbDadosMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMedicoMouseClicked
        // TODO add your handling code here:
        this.setEnebleAll();
        int linha = this.tbDadosMedico.getSelectedRow();
        String crm = String.valueOf(tbDadosMedico.getModel().getValueAt(linha, 0));
        String nome = String.valueOf(tbDadosMedico.getModel().getValueAt(linha, 1));
        String tel = String.valueOf(tbDadosMedico.getModel().getValueAt(linha, 2));
        String especialidade = String.valueOf(tbDadosMedico.getModel().getValueAt(linha, 3));
        
        jTcrm.setText(crm);
        jTNome1.setText(nome);
        jFtelefone1.setText(tel);
        jTespecialidade.setText(especialidade);
        
        jTNome1.setEnabled(true);
        jBsalvarM.setEnabled(true);
        //jBexcluirMd.setEnabled(true);
        
    }//GEN-LAST:event_tbDadosMedicoMouseClicked

    private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown
        // TODO add your handling code here:
        exibirDadosMedicos(tbDadosMedico);
    }//GEN-LAST:event_jPanel5ComponentShown

    private void cbEspecialidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEspecialidadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspecialidadeMouseClicked

    private void cbEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEspecialidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JTcpf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cbEspecialidade;
    private javax.swing.JComboBox<Object> cbMedico;
    private javax.swing.JComboBox<Object> cbPaciente;
    private javax.swing.JButton jBAtualizarQTN;
    private javax.swing.JButton jBadicionar;
    private javax.swing.JButton jBagConsultaCadMedico;
    private javax.swing.JButton jBagConsultaCadPaciente;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBcancelar1;
    private javax.swing.JButton jBcancelarConsulta;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBexcluirMd;
    private javax.swing.JButton jBexcluirconsulta;
    private javax.swing.JButton jBinserirConsulta;
    private javax.swing.JButton jBinserirM;
    private javax.swing.JButton jBinserirP;
    private javax.swing.JButton jBnovoP;
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JButton jBsalvarM;
    private javax.swing.JButton jBsalvarP;
    private javax.swing.JButton jBsalvararconsulta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFTelefone;
    private javax.swing.JFormattedTextField jFdatadaconsulta;
    private javax.swing.JFormattedTextField jFtelefone1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTEspecialidade2;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTNome1;
    private javax.swing.JTabbedPane jTabbedPaneAgConsulta;
    private javax.swing.JTextField jTcodconsulta;
    private javax.swing.JTextField jTcrm;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTespecialidade;
    private javax.swing.JTextField jTtotalconsultas;
    private javax.swing.JTable tbDadosConsulta;
    private javax.swing.JTable tbDadosMedico;
    private javax.swing.JTable tbDadosPaciente;
    private javax.swing.JTable tbQuantConsultas;
    // End of variables declaration//GEN-END:variables

   public void ListarPacientes(){
        CadastroPaciente cadPaciente= new CadastroPaciente();
        ArrayList<CadastroPaciente> dadospaciente = new ArrayList<>();
        dadospaciente = cadPaciente.ExibirPaciente();
        cbPaciente.removeAllItems();
        for (int i=0; i <dadospaciente.size(); i++){
            cbPaciente.addItem(dadospaciente.get(i).getCpf());
   
        }
   }
     public void ListarMedico(){
        CadastroMedico cadMedico= new CadastroMedico();
        ArrayList<CadastroMedico> dadosmedico = new ArrayList<>();
        dadosmedico = cadMedico.ExibirMedico(); 
        cbMedico.removeAllItems();
        for (int i=0; i <dadosmedico.size(); i++){
        cbMedico.addItem(dadosmedico.get(i).getCrm());
            
        }    
   }
    public void ListarEspecialidadMedico(){
        CadastroMedico cadMedico= new CadastroMedico();
        ArrayList<CadastroMedico> dadosmedico = new ArrayList<>();
        dadosmedico = cadMedico.ExibirMedico(); 
        cbEspecialidade.removeAllItems();
        for (int i=0; i <dadosmedico.size(); i++){
        cbEspecialidade.addItem(dadosmedico.get(i).getEspecialidade());
            
        }    
   }
     
    public void setEnebleAll(){
        cbMedico.setEnabled(true);
        cbPaciente.setEnabled(true);
        jFdatadaconsulta.setEnabled(true);     
        } 
    


     
        
   
}


